version: "3.12"

services:
  webapp:
    restart: unless-stopped
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: f7_patres
    depends_on:
      - db
    volumes:
      - ./tests:/app/tests
    command: [ "sh", "-c", "poetry run alembic upgrade head &&
                                              PYTHONPATH=/app poetry run pytest tests &&
                                              poetry run uvicorn src.main:app --host 0.0.0.0 --reload" ]

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: f7_patres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
