"""description changed

Revision ID: f08fd63a84c5
Revises: a72369b7f06f
Create Date: 2025-06-05 12:25:15.818938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f08fd63a84c5"
down_revision: Union[str, None] = "a72369b7f06f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Обновляем все NULL значения перед сменой nullable=False
    conn = op.get_bind()
    conn.execute(
        sa.text("UPDATE pat_book SET description = :default_value WHERE description IS NULL"),
        {"default_value": "Unknown"}
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pat_book", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pat_book", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
